### ISSUE TITLE
Reconsider syntax rules for empty/absent tag values

### ISSUE THREAD

**Issue by jotaen** [jotaen/xit#27]
Currently, the (draft!) spec [says about tag values](https://github.com/jotaen/xit/blob/main/Specification.md#tag):

> A tag MUST start with the hash character (`#`), followed by one or more characters for the name of the tag. There MAY follow an equals sign (`=`) along with one or more characters for the value of the tag.

Based on this, the following things cannot be written:

- `#tag=`
- `#tag=""`
- `#tag=''`

However, what does it mean that this cannot be written? Shall either the whole tag or the value part be marked as invalid? Or just be ignored?

On the one hand, `#tag=` etc. doesn’t have any “meaning”; on the other hand, it also doesn’t do any harm (as far as I see). So I suppose it eventually comes down to the question which is more convenient for both users and tool-builders.

Functionality-wise, these cases should behave the same as writing `#tag`, so absent tag value is the same as empty tag value.

## 1.) Allow tag values to be empty

One option would be to adjust the spec, to allow tag values to be empty:

> There MAY follow an equals sign (=) along with any number of characters for the value of the tag.

It then should also be clarified that empty tag value must be interpreted the same as absent tag value.

**Comment by delfiin** [comment]
Of course I'm thinking about it from my perspective.
I am parsing a line e.g. `it has #tags and more of #them=tags` into something like
```
{
  "#tags": true,
  "#them": "tags"
}
```
Without a value the equals sign doesn't make sense.
Also the spec says that tags can be enclosed by blanks or punctuation. Therefore *if* `=` is punctuation, we can just ignore it and parse the tag without, if not, I guess we could simply ignore it as an invalid tag like `a#tag`.

**Comment by jotaen** [comment]
I’ve actually also opened https://github.com/jotaen/xit/issues/28 as separate thing to clarify, because I’m not super happy with the phrasing of the rules which characters may appear around tags and due dates.
