### ISSUE TITLE
Rephrase rules for characters that may appear around tags or due dates

### ISSUE THREAD

**Issue by jotaen** [jotaen/xit#28]
The current [rules for what characters are allowed to appear around tags and due dates](https://github.com/jotaen/xit/blob/main/Specification.md#description) read somewhat complicated or obscure to me:

> The description MAY contain the following tokens:
> - One due date
> - Any number of tags
>
> These tokens MUST be surrounded by whitespace or punctuation, except for such punctuation which the tokens themselves can consist of.

At the end of the day, the underlying goal is to have simple and intuitive rules, that allow tags and due dates to appear naturally in the flow of a sentence, e.g.:

- `[ ] Do taxes (#work, #finances)`
- `[ ] Call #Mike: discuss weekend plans`
- `[ ] Paint fence -> 2022-04-18, Larry comes over to help`
- `[ ] Change tires (-> 2022-05-02)`

I suppose this can be explained in a more straightforward way.

**Comment by ryanolsonx** [comment]
I’ll say that having certain rules for what can show up before a due date has been tricky to implement in tooling (I’m thinking of my Vim syntax highlighting specifically). In a way, in my opinion, as long as they put something like “-> 2022-04-07” they should be good. Including: “——> 2022-04-07” and “Get taxes done->2022-04-07”.

**Comment by jotaen** [comment]
I think you are right that the rules shouldn’t be too strict.

This – just as reference data point – is how Twitter handles tag recognition:

<img width="583" alt="Screenshot 2022-04-10 at 15 04 12" src="https://user-images.githubusercontent.com/3618384/162619691-de38f833-9da8-45a7-9203-2f746cc3c445.png">

**Comment by ryanolsonx** [comment]
In a sense, with that as an example, it should only matter that we have a rule around when a tag or a due date should **end**, rather than start AND end.
