### ISSUE TITLE
Group descriptions below titles

### ISSUE THREAD

**Issue by jotaen** [jotaen/xit#45]
As [discussed here](https://github.com/jotaen/xit/discussions/10), an item group could have an additional, optional description underneath the headline, like so:

```
MONDAY
Today, I need to really need to take care
of the remaining tasks from last week!
[ ] File tax report
[ ] Wash up dishes
[ ] Watch new Netflix show
```

It would basically work like this:

- First line is the headline (as it is right now)
- Subsequent lines are interpreted to be group description
- First item ends the group description

Things that need to be decided and specified:

- Can the group description contain tags?
  - If so, they would have to implicitly apply to all items in that group.
- Does there have to be any restriction regarding the text itself? E.g.:
  - Like in titles, a line cannot start with `[`, to avoid ambiguity or confusion with items
  - Can lines start with whitespace, i.e. can they be “indented”? Could this cause problems?
  - Obviously, lines cannot be blank, because that would start a new group
- Like for descriptions, I wouldn’t want to introduce special syntax for text formatting or links.

**Comment by clach04** [comment]
One (not backwards compat) option would be to use Markdown headings for titles, i.e. `##` . This would conflict with https://github.com/jotaen/xit/discussions/46 though. The existing format is a superset of GFM tasklists already https://github.blog/2014-04-28-task-lists-in-all-markdown-documents/

>Can the group description contain tags? If so, would they apply to all items in the group?

If yes to initial question, I would assume yes for the second.

**Comment by jotaen** [comment]
> One (not backwards compat) option would be to use Markdown headings for titles, i.e. ## .

I’ve also thought about this, but I’m wondering whether there would be a benefit in making a `#` prefix mandatory for group titles. If one likes, the following is already possible:

```
# Todos
[ ] Item 1

=== Todos ===
[ ] Item 2
```

Another potential ambiguity might be that the `#` prefix could be confused with the syntax for tags. (Not super likely, though, probably.)

> If yes to initial question, I would assume yes for the second.

Yeah, I agree. It wouldn’t make sense if the group description could contain tags without them having any effect on the group’s items. I’ve rephrased the point above.

**Comment by jotaen** [comment]
I’m putting this on hold for now, see https://github.com/jotaen/xit/pull/55#issuecomment-1832816623.
